### ISSUE TITLE
Installation failed

### ISSUE THREAD

**Issue by Jocx-H** [SpRegTiling/spmm-bench#8]
When I used Dockerfile.artifactto build an image, I encountered the following error, it looks like a problem with the pytorch extension:

My version:
* pytorch: 2.4.0+cpu

```
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/spmm-nano-bench/setup.py", line 97, in <module>
        setuptools.setup(
      File "/opt/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
        return distutils.core.setup(**attrs)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
        return run_commands(dist)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
        dist.run_commands()
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
        self.run_command(cmd)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/dist.py", line 976, in run_command
        super().run_command(command)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/opt/venv/lib/python3.8/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/opt/venv/lib/python3.8/site-packages/setuptools/command/develop.py", line 113, in install_for_development
        self.run_command('build_ext')
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/dist.py", line 976, in run_command
        super().run_command(command)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
        cmd_obj.run()
      File "/opt/venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 93, in run
        _build_ext.run(self)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
        self.build_extensions()
      File "/opt/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
        build_ext.build_extensions(self)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
        self._build_extensions_serial()
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
        self.build_extension(ext)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
        _build_ext.build_extension(self, ext)
      File "/opt/venv/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
        objects = self.compiler.compile(
      File "/opt/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/opt/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/opt/venv/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
```

**Comment by LucasWilkinson** [comment]
@Jocx-H Apologies for the delay! can you please provide a full log, unfortunately this one cuts off the build error
